/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Object containing metadata about the interest rate for the mortgage.
    /// </summary>
    [DataContract(Name = "MortgageInterestRate")]
    public partial class MortgageInterestRate : Dictionary<String, Object>, IEquatable<MortgageInterestRate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MortgageInterestRate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MortgageInterestRate()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MortgageInterestRate" /> class.
        /// </summary>
        /// <param name="percentage">Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan. (required).</param>
        /// <param name="type">The type of interest charged (fixed or variable). (required).</param>
        public MortgageInterestRate(decimal? percentage = default(decimal?), string type = default(string)) : base()
        {
            // to ensure "percentage" is required (not null)
            if (percentage == null)
            {
                throw new ArgumentNullException("percentage is a required property for MortgageInterestRate and cannot be null");
            }
            this.Percentage = percentage;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for MortgageInterestRate and cannot be null");
            }
            this.Type = type;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan.
        /// </summary>
        /// <value>Percentage value (interest rate of current mortgage, not APR) of interest payable on a loan.</value>
        [DataMember(Name = "percentage", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Percentage { get; set; }

        /// <summary>
        /// The type of interest charged (fixed or variable).
        /// </summary>
        /// <value>The type of interest charged (fixed or variable).</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MortgageInterestRate {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Percentage: ").Append(Percentage).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MortgageInterestRate);
        }

        /// <summary>
        /// Returns true if MortgageInterestRate instances are equal
        /// </summary>
        /// <param name="input">Instance of MortgageInterestRate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MortgageInterestRate input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Percentage == input.Percentage ||
                    (this.Percentage != null &&
                    this.Percentage.Equals(input.Percentage))
                ) && base.Equals(input) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Percentage != null)
                {
                    hashCode = (hashCode * 59) + this.Percentage.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
