/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountBaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountBase
        //private AccountBase instance;

        public AccountBaseTests()
        {
            // TODO uncomment below to create an instance of AccountBase
            //instance = new AccountBase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountBase
        /// </summary>
        [Fact]
        public void AccountBaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountBase
            //Assert.IsType<AccountBase>(instance);
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Fact]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }
        /// <summary>
        /// Test the property 'Mask'
        /// </summary>
        [Fact]
        public void MaskTest()
        {
            // TODO unit test for the property 'Mask'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OfficialName'
        /// </summary>
        [Fact]
        public void OfficialNameTest()
        {
            // TODO unit test for the property 'OfficialName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Subtype'
        /// </summary>
        [Fact]
        public void SubtypeTest()
        {
            // TODO unit test for the property 'Subtype'
        }
        /// <summary>
        /// Test the property 'VerificationStatus'
        /// </summary>
        [Fact]
        public void VerificationStatusTest()
        {
            // TODO unit test for the property 'VerificationStatus'
        }

    }

}
