/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountFiltersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountFiltersResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountFiltersResponse
        //private AccountFiltersResponse instance;

        public AccountFiltersResponseTests()
        {
            // TODO uncomment below to create an instance of AccountFiltersResponse
            //instance = new AccountFiltersResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountFiltersResponse
        /// </summary>
        [Fact]
        public void AccountFiltersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountFiltersResponse
            //Assert.IsType<AccountFiltersResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Depository'
        /// </summary>
        [Fact]
        public void DepositoryTest()
        {
            // TODO unit test for the property 'Depository'
        }
        /// <summary>
        /// Test the property 'Credit'
        /// </summary>
        [Fact]
        public void CreditTest()
        {
            // TODO unit test for the property 'Credit'
        }
        /// <summary>
        /// Test the property 'Loan'
        /// </summary>
        [Fact]
        public void LoanTest()
        {
            // TODO unit test for the property 'Loan'
        }
        /// <summary>
        /// Test the property 'Investment'
        /// </summary>
        [Fact]
        public void InvestmentTest()
        {
            // TODO unit test for the property 'Investment'
        }

    }

}
