/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountProductAccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountProductAccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountProductAccess
        //private AccountProductAccess instance;

        public AccountProductAccessTests()
        {
            // TODO uncomment below to create an instance of AccountProductAccess
            //instance = new AccountProductAccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountProductAccess
        /// </summary>
        [Fact]
        public void AccountProductAccessInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountProductAccess
            //Assert.IsType<AccountProductAccess>(instance);
        }


        /// <summary>
        /// Test the property 'AccountData'
        /// </summary>
        [Fact]
        public void AccountDataTest()
        {
            // TODO unit test for the property 'AccountData'
        }
        /// <summary>
        /// Test the property 'Statements'
        /// </summary>
        [Fact]
        public void StatementsTest()
        {
            // TODO unit test for the property 'Statements'
        }
        /// <summary>
        /// Test the property 'TaxDocuments'
        /// </summary>
        [Fact]
        public void TaxDocumentsTest()
        {
            // TODO unit test for the property 'TaxDocuments'
        }

    }

}
