/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssetReportGetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetReportGetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetReportGetRequest
        //private AssetReportGetRequest instance;

        public AssetReportGetRequestTests()
        {
            // TODO uncomment below to create an instance of AssetReportGetRequest
            //instance = new AssetReportGetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetReportGetRequest
        /// </summary>
        [Fact]
        public void AssetReportGetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetReportGetRequest
            //Assert.IsType<AssetReportGetRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'AssetReportToken'
        /// </summary>
        [Fact]
        public void AssetReportTokenTest()
        {
            // TODO unit test for the property 'AssetReportToken'
        }
        /// <summary>
        /// Test the property 'IncludeInsights'
        /// </summary>
        [Fact]
        public void IncludeInsightsTest()
        {
            // TODO unit test for the property 'IncludeInsights'
        }

    }

}
