/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BankTransferSweepGetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankTransferSweepGetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankTransferSweepGetRequest
        //private BankTransferSweepGetRequest instance;

        public BankTransferSweepGetRequestTests()
        {
            // TODO uncomment below to create an instance of BankTransferSweepGetRequest
            //instance = new BankTransferSweepGetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankTransferSweepGetRequest
        /// </summary>
        [Fact]
        public void BankTransferSweepGetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankTransferSweepGetRequest
            //Assert.IsType<BankTransferSweepGetRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'SweepId'
        /// </summary>
        [Fact]
        public void SweepIdTest()
        {
            // TODO unit test for the property 'SweepId'
        }

    }

}
