/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BankTransferEventListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankTransferEventListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankTransferEventListRequest
        //private BankTransferEventListRequest instance;

        public BankTransferEventListRequestTests()
        {
            // TODO uncomment below to create an instance of BankTransferEventListRequest
            //instance = new BankTransferEventListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankTransferEventListRequest
        /// </summary>
        [Fact]
        public void BankTransferEventListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankTransferEventListRequest
            //Assert.IsType<BankTransferEventListRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'BankTransferId'
        /// </summary>
        [Fact]
        public void BankTransferIdTest()
        {
            // TODO unit test for the property 'BankTransferId'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'BankTransferType'
        /// </summary>
        [Fact]
        public void BankTransferTypeTest()
        {
            // TODO unit test for the property 'BankTransferType'
        }
        /// <summary>
        /// Test the property 'EventTypes'
        /// </summary>
        [Fact]
        public void EventTypesTest()
        {
            // TODO unit test for the property 'EventTypes'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'OriginationAccountId'
        /// </summary>
        [Fact]
        public void OriginationAccountIdTest()
        {
            // TODO unit test for the property 'OriginationAccountId'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }

    }

}
