/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BankTransferDirection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankTransferDirectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankTransferDirection
        //private BankTransferDirection instance;

        public BankTransferDirectionTests()
        {
            // TODO uncomment below to create an instance of BankTransferDirection
            //instance = new BankTransferDirection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankTransferDirection
        /// </summary>
        [Fact]
        public void BankTransferDirectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankTransferDirection
            //Assert.IsType<BankTransferDirection>(instance);
        }



    }

}
