/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocType
        //private DocType instance;

        public DocTypeTests()
        {
            // TODO uncomment below to create an instance of DocType
            //instance = new DocType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocType
        /// </summary>
        [Fact]
        public void DocTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocType
            //Assert.IsType<DocType>(instance);
        }



    }

}
