/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EarningsBreakdown
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EarningsBreakdownTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EarningsBreakdown
        //private EarningsBreakdown instance;

        public EarningsBreakdownTests()
        {
            // TODO uncomment below to create an instance of EarningsBreakdown
            //instance = new EarningsBreakdown();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EarningsBreakdown
        /// </summary>
        [Fact]
        public void EarningsBreakdownInstanceTest()
        {
            // TODO uncomment below to test "IsType" EarningsBreakdown
            //Assert.IsType<EarningsBreakdown>(instance);
        }


        /// <summary>
        /// Test the property 'CanonicalDescription'
        /// </summary>
        [Fact]
        public void CanonicalDescriptionTest()
        {
            // TODO unit test for the property 'CanonicalDescription'
        }
        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Fact]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }
        /// <summary>
        /// Test the property 'IsoCurrencyCode'
        /// </summary>
        [Fact]
        public void IsoCurrencyCodeTest()
        {
            // TODO unit test for the property 'IsoCurrencyCode'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'UnofficialCurrencyCode'
        /// </summary>
        [Fact]
        public void UnofficialCurrencyCodeTest()
        {
            // TODO unit test for the property 'UnofficialCurrencyCode'
        }
        /// <summary>
        /// Test the property 'YtdAmount'
        /// </summary>
        [Fact]
        public void YtdAmountTest()
        {
            // TODO unit test for the property 'YtdAmount'
        }

    }

}
