/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IncomeSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IncomeSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IncomeSummary
        //private IncomeSummary instance;

        public IncomeSummaryTests()
        {
            // TODO uncomment below to create an instance of IncomeSummary
            //instance = new IncomeSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IncomeSummary
        /// </summary>
        [Fact]
        public void IncomeSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" IncomeSummary
            //Assert.IsType<IncomeSummary>(instance);
        }


        /// <summary>
        /// Test the property 'EmployerName'
        /// </summary>
        [Fact]
        public void EmployerNameTest()
        {
            // TODO unit test for the property 'EmployerName'
        }
        /// <summary>
        /// Test the property 'EmployeeName'
        /// </summary>
        [Fact]
        public void EmployeeNameTest()
        {
            // TODO unit test for the property 'EmployeeName'
        }
        /// <summary>
        /// Test the property 'YtdGrossIncome'
        /// </summary>
        [Fact]
        public void YtdGrossIncomeTest()
        {
            // TODO unit test for the property 'YtdGrossIncome'
        }
        /// <summary>
        /// Test the property 'YtdNetIncome'
        /// </summary>
        [Fact]
        public void YtdNetIncomeTest()
        {
            // TODO unit test for the property 'YtdNetIncome'
        }
        /// <summary>
        /// Test the property 'PayFrequency'
        /// </summary>
        [Fact]
        public void PayFrequencyTest()
        {
            // TODO unit test for the property 'PayFrequency'
        }
        /// <summary>
        /// Test the property 'ProjectedWage'
        /// </summary>
        [Fact]
        public void ProjectedWageTest()
        {
            // TODO unit test for the property 'ProjectedWage'
        }
        /// <summary>
        /// Test the property 'VerifiedTransaction'
        /// </summary>
        [Fact]
        public void VerifiedTransactionTest()
        {
            // TODO unit test for the property 'VerifiedTransaction'
        }

    }

}
