/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InvestmentsTransactionsGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvestmentsTransactionsGetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvestmentsTransactionsGetResponse
        //private InvestmentsTransactionsGetResponse instance;

        public InvestmentsTransactionsGetResponseTests()
        {
            // TODO uncomment below to create an instance of InvestmentsTransactionsGetResponse
            //instance = new InvestmentsTransactionsGetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvestmentsTransactionsGetResponse
        /// </summary>
        [Fact]
        public void InvestmentsTransactionsGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvestmentsTransactionsGetResponse
            //Assert.IsType<InvestmentsTransactionsGetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Accounts'
        /// </summary>
        [Fact]
        public void AccountsTest()
        {
            // TODO unit test for the property 'Accounts'
        }
        /// <summary>
        /// Test the property 'Securities'
        /// </summary>
        [Fact]
        public void SecuritiesTest()
        {
            // TODO unit test for the property 'Securities'
        }
        /// <summary>
        /// Test the property 'InvestmentTransactions'
        /// </summary>
        [Fact]
        public void InvestmentTransactionsTest()
        {
            // TODO unit test for the property 'InvestmentTransactions'
        }
        /// <summary>
        /// Test the property 'TotalInvestmentTransactions'
        /// </summary>
        [Fact]
        public void TotalInvestmentTransactionsTest()
        {
            // TODO unit test for the property 'TotalInvestmentTransactions'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
