/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ItemProductReadyWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemProductReadyWebhookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemProductReadyWebhook
        //private ItemProductReadyWebhook instance;

        public ItemProductReadyWebhookTests()
        {
            // TODO uncomment below to create an instance of ItemProductReadyWebhook
            //instance = new ItemProductReadyWebhook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemProductReadyWebhook
        /// </summary>
        [Fact]
        public void ItemProductReadyWebhookInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemProductReadyWebhook
            //Assert.IsType<ItemProductReadyWebhook>(instance);
        }


        /// <summary>
        /// Test the property 'WebhookType'
        /// </summary>
        [Fact]
        public void WebhookTypeTest()
        {
            // TODO unit test for the property 'WebhookType'
        }
        /// <summary>
        /// Test the property 'WebhookCode'
        /// </summary>
        [Fact]
        public void WebhookCodeTest()
        {
            // TODO unit test for the property 'WebhookCode'
        }
        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Fact]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
