/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LiabilityOverride
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LiabilityOverrideTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LiabilityOverride
        //private LiabilityOverride instance;

        public LiabilityOverrideTests()
        {
            // TODO uncomment below to create an instance of LiabilityOverride
            //instance = new LiabilityOverride();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LiabilityOverride
        /// </summary>
        [Fact]
        public void LiabilityOverrideInstanceTest()
        {
            // TODO uncomment below to test "IsType" LiabilityOverride
            //Assert.IsType<LiabilityOverride>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'PurchaseApr'
        /// </summary>
        [Fact]
        public void PurchaseAprTest()
        {
            // TODO unit test for the property 'PurchaseApr'
        }
        /// <summary>
        /// Test the property 'CashApr'
        /// </summary>
        [Fact]
        public void CashAprTest()
        {
            // TODO unit test for the property 'CashApr'
        }
        /// <summary>
        /// Test the property 'BalanceTransferApr'
        /// </summary>
        [Fact]
        public void BalanceTransferAprTest()
        {
            // TODO unit test for the property 'BalanceTransferApr'
        }
        /// <summary>
        /// Test the property 'SpecialApr'
        /// </summary>
        [Fact]
        public void SpecialAprTest()
        {
            // TODO unit test for the property 'SpecialApr'
        }
        /// <summary>
        /// Test the property 'LastPaymentAmount'
        /// </summary>
        [Fact]
        public void LastPaymentAmountTest()
        {
            // TODO unit test for the property 'LastPaymentAmount'
        }
        /// <summary>
        /// Test the property 'MinimumPaymentAmount'
        /// </summary>
        [Fact]
        public void MinimumPaymentAmountTest()
        {
            // TODO unit test for the property 'MinimumPaymentAmount'
        }
        /// <summary>
        /// Test the property 'IsOverdue'
        /// </summary>
        [Fact]
        public void IsOverdueTest()
        {
            // TODO unit test for the property 'IsOverdue'
        }
        /// <summary>
        /// Test the property 'OriginationDate'
        /// </summary>
        [Fact]
        public void OriginationDateTest()
        {
            // TODO unit test for the property 'OriginationDate'
        }
        /// <summary>
        /// Test the property 'Principal'
        /// </summary>
        [Fact]
        public void PrincipalTest()
        {
            // TODO unit test for the property 'Principal'
        }
        /// <summary>
        /// Test the property 'NominalApr'
        /// </summary>
        [Fact]
        public void NominalAprTest()
        {
            // TODO unit test for the property 'NominalApr'
        }
        /// <summary>
        /// Test the property 'InterestCapitalizationGracePeriodMonths'
        /// </summary>
        [Fact]
        public void InterestCapitalizationGracePeriodMonthsTest()
        {
            // TODO unit test for the property 'InterestCapitalizationGracePeriodMonths'
        }
        /// <summary>
        /// Test the property 'RepaymentModel'
        /// </summary>
        [Fact]
        public void RepaymentModelTest()
        {
            // TODO unit test for the property 'RepaymentModel'
        }
        /// <summary>
        /// Test the property 'ExpectedPayoffDate'
        /// </summary>
        [Fact]
        public void ExpectedPayoffDateTest()
        {
            // TODO unit test for the property 'ExpectedPayoffDate'
        }
        /// <summary>
        /// Test the property 'Guarantor'
        /// </summary>
        [Fact]
        public void GuarantorTest()
        {
            // TODO unit test for the property 'Guarantor'
        }
        /// <summary>
        /// Test the property 'IsFederal'
        /// </summary>
        [Fact]
        public void IsFederalTest()
        {
            // TODO unit test for the property 'IsFederal'
        }
        /// <summary>
        /// Test the property 'LoanName'
        /// </summary>
        [Fact]
        public void LoanNameTest()
        {
            // TODO unit test for the property 'LoanName'
        }
        /// <summary>
        /// Test the property 'LoanStatus'
        /// </summary>
        [Fact]
        public void LoanStatusTest()
        {
            // TODO unit test for the property 'LoanStatus'
        }
        /// <summary>
        /// Test the property 'PaymentReferenceNumber'
        /// </summary>
        [Fact]
        public void PaymentReferenceNumberTest()
        {
            // TODO unit test for the property 'PaymentReferenceNumber'
        }
        /// <summary>
        /// Test the property 'PslfStatus'
        /// </summary>
        [Fact]
        public void PslfStatusTest()
        {
            // TODO unit test for the property 'PslfStatus'
        }
        /// <summary>
        /// Test the property 'RepaymentPlanDescription'
        /// </summary>
        [Fact]
        public void RepaymentPlanDescriptionTest()
        {
            // TODO unit test for the property 'RepaymentPlanDescription'
        }
        /// <summary>
        /// Test the property 'RepaymentPlanType'
        /// </summary>
        [Fact]
        public void RepaymentPlanTypeTest()
        {
            // TODO unit test for the property 'RepaymentPlanType'
        }
        /// <summary>
        /// Test the property 'SequenceNumber'
        /// </summary>
        [Fact]
        public void SequenceNumberTest()
        {
            // TODO unit test for the property 'SequenceNumber'
        }
        /// <summary>
        /// Test the property 'ServicerAddress'
        /// </summary>
        [Fact]
        public void ServicerAddressTest()
        {
            // TODO unit test for the property 'ServicerAddress'
        }

    }

}
