/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LinkTokenCreateRequestDepositSwitch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkTokenCreateRequestDepositSwitchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkTokenCreateRequestDepositSwitch
        //private LinkTokenCreateRequestDepositSwitch instance;

        public LinkTokenCreateRequestDepositSwitchTests()
        {
            // TODO uncomment below to create an instance of LinkTokenCreateRequestDepositSwitch
            //instance = new LinkTokenCreateRequestDepositSwitch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkTokenCreateRequestDepositSwitch
        /// </summary>
        [Fact]
        public void LinkTokenCreateRequestDepositSwitchInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkTokenCreateRequestDepositSwitch
            //Assert.IsType<LinkTokenCreateRequestDepositSwitch>(instance);
        }


        /// <summary>
        /// Test the property 'DepositSwitchId'
        /// </summary>
        [Fact]
        public void DepositSwitchIdTest()
        {
            // TODO unit test for the property 'DepositSwitchId'
        }

    }

}
