/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MFA
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MFATests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MFA
        //private MFA instance;

        public MFATests()
        {
            // TODO uncomment below to create an instance of MFA
            //instance = new MFA();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MFA
        /// </summary>
        [Fact]
        public void MFAInstanceTest()
        {
            // TODO uncomment below to test "IsType" MFA
            //Assert.IsType<MFA>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'QuestionRounds'
        /// </summary>
        [Fact]
        public void QuestionRoundsTest()
        {
            // TODO unit test for the property 'QuestionRounds'
        }
        /// <summary>
        /// Test the property 'QuestionsPerRound'
        /// </summary>
        [Fact]
        public void QuestionsPerRoundTest()
        {
            // TODO unit test for the property 'QuestionsPerRound'
        }
        /// <summary>
        /// Test the property 'SelectionRounds'
        /// </summary>
        [Fact]
        public void SelectionRoundsTest()
        {
            // TODO unit test for the property 'SelectionRounds'
        }
        /// <summary>
        /// Test the property 'SelectionsPerQuestion'
        /// </summary>
        [Fact]
        public void SelectionsPerQuestionTest()
        {
            // TODO unit test for the property 'SelectionsPerQuestion'
        }

    }

}
