/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NetPay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetPayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetPay
        //private NetPay instance;

        public NetPayTests()
        {
            // TODO uncomment below to create an instance of NetPay
            //instance = new NetPay();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetPay
        /// </summary>
        [Fact]
        public void NetPayInstanceTest()
        {
            // TODO uncomment below to test "IsType" NetPay
            //Assert.IsType<NetPay>(instance);
        }


        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsoCurrencyCode'
        /// </summary>
        [Fact]
        public void IsoCurrencyCodeTest()
        {
            // TODO unit test for the property 'IsoCurrencyCode'
        }
        /// <summary>
        /// Test the property 'UnofficialCurrencyCode'
        /// </summary>
        [Fact]
        public void UnofficialCurrencyCodeTest()
        {
            // TODO unit test for the property 'UnofficialCurrencyCode'
        }
        /// <summary>
        /// Test the property 'YtdAmount'
        /// </summary>
        [Fact]
        public void YtdAmountTest()
        {
            // TODO unit test for the property 'YtdAmount'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
