/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NumbersInternationalNullable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NumbersInternationalNullableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NumbersInternationalNullable
        //private NumbersInternationalNullable instance;

        public NumbersInternationalNullableTests()
        {
            // TODO uncomment below to create an instance of NumbersInternationalNullable
            //instance = new NumbersInternationalNullable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NumbersInternationalNullable
        /// </summary>
        [Fact]
        public void NumbersInternationalNullableInstanceTest()
        {
            // TODO uncomment below to test "IsType" NumbersInternationalNullable
            //Assert.IsType<NumbersInternationalNullable>(instance);
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'Bic'
        /// </summary>
        [Fact]
        public void BicTest()
        {
            // TODO unit test for the property 'Bic'
        }

    }

}
