/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Owner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OwnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Owner
        //private Owner instance;

        public OwnerTests()
        {
            // TODO uncomment below to create an instance of Owner
            //instance = new Owner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Owner
        /// </summary>
        [Fact]
        public void OwnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Owner
            //Assert.IsType<Owner>(instance);
        }


        /// <summary>
        /// Test the property 'Names'
        /// </summary>
        [Fact]
        public void NamesTest()
        {
            // TODO unit test for the property 'Names'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Fact]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }

    }

}
