/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentInitiationPaymentListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentInitiationPaymentListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentInitiationPaymentListResponse
        //private PaymentInitiationPaymentListResponse instance;

        public PaymentInitiationPaymentListResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentInitiationPaymentListResponse
            //instance = new PaymentInitiationPaymentListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentInitiationPaymentListResponse
        /// </summary>
        [Fact]
        public void PaymentInitiationPaymentListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentInitiationPaymentListResponse
            //Assert.IsType<PaymentInitiationPaymentListResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Fact]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }
        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
