/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentInitiationRefund
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentInitiationRefundTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentInitiationRefund
        //private PaymentInitiationRefund instance;

        public PaymentInitiationRefundTests()
        {
            // TODO uncomment below to create an instance of PaymentInitiationRefund
            //instance = new PaymentInitiationRefund();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentInitiationRefund
        /// </summary>
        [Fact]
        public void PaymentInitiationRefundInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentInitiationRefund
            //Assert.IsType<PaymentInitiationRefund>(instance);
        }


        /// <summary>
        /// Test the property 'RefundId'
        /// </summary>
        [Fact]
        public void RefundIdTest()
        {
            // TODO unit test for the property 'RefundId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastStatusUpdate'
        /// </summary>
        [Fact]
        public void LastStatusUpdateTest()
        {
            // TODO unit test for the property 'LastStatusUpdate'
        }

    }

}
