/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentInitiationMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentInitiationMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentInitiationMetadata
        //private PaymentInitiationMetadata instance;

        public PaymentInitiationMetadataTests()
        {
            // TODO uncomment below to create an instance of PaymentInitiationMetadata
            //instance = new PaymentInitiationMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentInitiationMetadata
        /// </summary>
        [Fact]
        public void PaymentInitiationMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentInitiationMetadata
            //Assert.IsType<PaymentInitiationMetadata>(instance);
        }


        /// <summary>
        /// Test the property 'SupportsInternationalPayments'
        /// </summary>
        [Fact]
        public void SupportsInternationalPaymentsTest()
        {
            // TODO unit test for the property 'SupportsInternationalPayments'
        }
        /// <summary>
        /// Test the property 'MaximumPaymentAmount'
        /// </summary>
        [Fact]
        public void MaximumPaymentAmountTest()
        {
            // TODO unit test for the property 'MaximumPaymentAmount'
        }
        /// <summary>
        /// Test the property 'SupportsRefundDetails'
        /// </summary>
        [Fact]
        public void SupportsRefundDetailsTest()
        {
            // TODO unit test for the property 'SupportsRefundDetails'
        }
        /// <summary>
        /// Test the property 'StandingOrderMetadata'
        /// </summary>
        [Fact]
        public void StandingOrderMetadataTest()
        {
            // TODO unit test for the property 'StandingOrderMetadata'
        }

    }

}
