/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaystubYTDDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaystubYTDDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaystubYTDDetails
        //private PaystubYTDDetails instance;

        public PaystubYTDDetailsTests()
        {
            // TODO uncomment below to create an instance of PaystubYTDDetails
            //instance = new PaystubYTDDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaystubYTDDetails
        /// </summary>
        [Fact]
        public void PaystubYTDDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaystubYTDDetails
            //Assert.IsType<PaystubYTDDetails>(instance);
        }


        /// <summary>
        /// Test the property 'GrossEarnings'
        /// </summary>
        [Fact]
        public void GrossEarningsTest()
        {
            // TODO unit test for the property 'GrossEarnings'
        }
        /// <summary>
        /// Test the property 'NetEarnings'
        /// </summary>
        [Fact]
        public void NetEarningsTest()
        {
            // TODO unit test for the property 'NetEarnings'
        }

    }

}
