/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SandboxTransferSimulateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SandboxTransferSimulateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SandboxTransferSimulateRequest
        //private SandboxTransferSimulateRequest instance;

        public SandboxTransferSimulateRequestTests()
        {
            // TODO uncomment below to create an instance of SandboxTransferSimulateRequest
            //instance = new SandboxTransferSimulateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SandboxTransferSimulateRequest
        /// </summary>
        [Fact]
        public void SandboxTransferSimulateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SandboxTransferSimulateRequest
            //Assert.IsType<SandboxTransferSimulateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'TransferId'
        /// </summary>
        [Fact]
        public void TransferIdTest()
        {
            // TODO unit test for the property 'TransferId'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Fact]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }

    }

}
