/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Security
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecurityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Security
        //private Security instance;

        public SecurityTests()
        {
            // TODO uncomment below to create an instance of Security
            //instance = new Security();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Security
        /// </summary>
        [Fact]
        public void SecurityInstanceTest()
        {
            // TODO uncomment below to test "IsType" Security
            //Assert.IsType<Security>(instance);
        }


        /// <summary>
        /// Test the property 'SecurityId'
        /// </summary>
        [Fact]
        public void SecurityIdTest()
        {
            // TODO unit test for the property 'SecurityId'
        }
        /// <summary>
        /// Test the property 'Isin'
        /// </summary>
        [Fact]
        public void IsinTest()
        {
            // TODO unit test for the property 'Isin'
        }
        /// <summary>
        /// Test the property 'Cusip'
        /// </summary>
        [Fact]
        public void CusipTest()
        {
            // TODO unit test for the property 'Cusip'
        }
        /// <summary>
        /// Test the property 'Sedol'
        /// </summary>
        [Fact]
        public void SedolTest()
        {
            // TODO unit test for the property 'Sedol'
        }
        /// <summary>
        /// Test the property 'InstitutionSecurityId'
        /// </summary>
        [Fact]
        public void InstitutionSecurityIdTest()
        {
            // TODO unit test for the property 'InstitutionSecurityId'
        }
        /// <summary>
        /// Test the property 'InstitutionId'
        /// </summary>
        [Fact]
        public void InstitutionIdTest()
        {
            // TODO unit test for the property 'InstitutionId'
        }
        /// <summary>
        /// Test the property 'ProxySecurityId'
        /// </summary>
        [Fact]
        public void ProxySecurityIdTest()
        {
            // TODO unit test for the property 'ProxySecurityId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TickerSymbol'
        /// </summary>
        [Fact]
        public void TickerSymbolTest()
        {
            // TODO unit test for the property 'TickerSymbol'
        }
        /// <summary>
        /// Test the property 'IsCashEquivalent'
        /// </summary>
        [Fact]
        public void IsCashEquivalentTest()
        {
            // TODO unit test for the property 'IsCashEquivalent'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ClosePrice'
        /// </summary>
        [Fact]
        public void ClosePriceTest()
        {
            // TODO unit test for the property 'ClosePrice'
        }
        /// <summary>
        /// Test the property 'ClosePriceAsOf'
        /// </summary>
        [Fact]
        public void ClosePriceAsOfTest()
        {
            // TODO unit test for the property 'ClosePriceAsOf'
        }
        /// <summary>
        /// Test the property 'IsoCurrencyCode'
        /// </summary>
        [Fact]
        public void IsoCurrencyCodeTest()
        {
            // TODO unit test for the property 'IsoCurrencyCode'
        }
        /// <summary>
        /// Test the property 'UnofficialCurrencyCode'
        /// </summary>
        [Fact]
        public void UnofficialCurrencyCodeTest()
        {
            // TODO unit test for the property 'UnofficialCurrencyCode'
        }

    }

}
