/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SignalEvaluateCoreAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignalEvaluateCoreAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignalEvaluateCoreAttributes
        //private SignalEvaluateCoreAttributes instance;

        public SignalEvaluateCoreAttributesTests()
        {
            // TODO uncomment below to create an instance of SignalEvaluateCoreAttributes
            //instance = new SignalEvaluateCoreAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignalEvaluateCoreAttributes
        /// </summary>
        [Fact]
        public void SignalEvaluateCoreAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignalEvaluateCoreAttributes
            //Assert.IsType<SignalEvaluateCoreAttributes>(instance);
        }


        /// <summary>
        /// Test the property 'UnauthorizedTransactionsCount7d'
        /// </summary>
        [Fact]
        public void UnauthorizedTransactionsCount7dTest()
        {
            // TODO unit test for the property 'UnauthorizedTransactionsCount7d'
        }
        /// <summary>
        /// Test the property 'UnauthorizedTransactionsCount30d'
        /// </summary>
        [Fact]
        public void UnauthorizedTransactionsCount30dTest()
        {
            // TODO unit test for the property 'UnauthorizedTransactionsCount30d'
        }
        /// <summary>
        /// Test the property 'UnauthorizedTransactionsCount60d'
        /// </summary>
        [Fact]
        public void UnauthorizedTransactionsCount60dTest()
        {
            // TODO unit test for the property 'UnauthorizedTransactionsCount60d'
        }
        /// <summary>
        /// Test the property 'UnauthorizedTransactionsCount90d'
        /// </summary>
        [Fact]
        public void UnauthorizedTransactionsCount90dTest()
        {
            // TODO unit test for the property 'UnauthorizedTransactionsCount90d'
        }
        /// <summary>
        /// Test the property 'NsfOverdraftTransactionsCount7d'
        /// </summary>
        [Fact]
        public void NsfOverdraftTransactionsCount7dTest()
        {
            // TODO unit test for the property 'NsfOverdraftTransactionsCount7d'
        }
        /// <summary>
        /// Test the property 'NsfOverdraftTransactionsCount30d'
        /// </summary>
        [Fact]
        public void NsfOverdraftTransactionsCount30dTest()
        {
            // TODO unit test for the property 'NsfOverdraftTransactionsCount30d'
        }
        /// <summary>
        /// Test the property 'NsfOverdraftTransactionsCount60d'
        /// </summary>
        [Fact]
        public void NsfOverdraftTransactionsCount60dTest()
        {
            // TODO unit test for the property 'NsfOverdraftTransactionsCount60d'
        }
        /// <summary>
        /// Test the property 'NsfOverdraftTransactionsCount90d'
        /// </summary>
        [Fact]
        public void NsfOverdraftTransactionsCount90dTest()
        {
            // TODO unit test for the property 'NsfOverdraftTransactionsCount90d'
        }
        /// <summary>
        /// Test the property 'DaysSinceFirstPlaidConnection'
        /// </summary>
        [Fact]
        public void DaysSinceFirstPlaidConnectionTest()
        {
            // TODO unit test for the property 'DaysSinceFirstPlaidConnection'
        }
        /// <summary>
        /// Test the property 'PlaidConnectionsCount7d'
        /// </summary>
        [Fact]
        public void PlaidConnectionsCount7dTest()
        {
            // TODO unit test for the property 'PlaidConnectionsCount7d'
        }
        /// <summary>
        /// Test the property 'PlaidConnectionsCount30d'
        /// </summary>
        [Fact]
        public void PlaidConnectionsCount30dTest()
        {
            // TODO unit test for the property 'PlaidConnectionsCount30d'
        }
        /// <summary>
        /// Test the property 'TotalPlaidConnectionsCount'
        /// </summary>
        [Fact]
        public void TotalPlaidConnectionsCountTest()
        {
            // TODO unit test for the property 'TotalPlaidConnectionsCount'
        }
        /// <summary>
        /// Test the property 'IsSavingsOrMoneyMarketAccount'
        /// </summary>
        [Fact]
        public void IsSavingsOrMoneyMarketAccountTest()
        {
            // TODO unit test for the property 'IsSavingsOrMoneyMarketAccount'
        }
        /// <summary>
        /// Test the property 'TotalCreditTransactionsAmount10d'
        /// </summary>
        [Fact]
        public void TotalCreditTransactionsAmount10dTest()
        {
            // TODO unit test for the property 'TotalCreditTransactionsAmount10d'
        }
        /// <summary>
        /// Test the property 'TotalDebitTransactionsAmount10d'
        /// </summary>
        [Fact]
        public void TotalDebitTransactionsAmount10dTest()
        {
            // TODO unit test for the property 'TotalDebitTransactionsAmount10d'
        }
        /// <summary>
        /// Test the property 'P50CreditTransactionsAmount28d'
        /// </summary>
        [Fact]
        public void P50CreditTransactionsAmount28dTest()
        {
            // TODO unit test for the property 'P50CreditTransactionsAmount28d'
        }
        /// <summary>
        /// Test the property 'P50DebitTransactionsAmount28d'
        /// </summary>
        [Fact]
        public void P50DebitTransactionsAmount28dTest()
        {
            // TODO unit test for the property 'P50DebitTransactionsAmount28d'
        }
        /// <summary>
        /// Test the property 'P95CreditTransactionsAmount28d'
        /// </summary>
        [Fact]
        public void P95CreditTransactionsAmount28dTest()
        {
            // TODO unit test for the property 'P95CreditTransactionsAmount28d'
        }
        /// <summary>
        /// Test the property 'P95DebitTransactionsAmount28d'
        /// </summary>
        [Fact]
        public void P95DebitTransactionsAmount28dTest()
        {
            // TODO unit test for the property 'P95DebitTransactionsAmount28d'
        }
        /// <summary>
        /// Test the property 'DaysWithNegativeBalanceCount90d'
        /// </summary>
        [Fact]
        public void DaysWithNegativeBalanceCount90dTest()
        {
            // TODO unit test for the property 'DaysWithNegativeBalanceCount90d'
        }
        /// <summary>
        /// Test the property 'P90EodBalance30d'
        /// </summary>
        [Fact]
        public void P90EodBalance30dTest()
        {
            // TODO unit test for the property 'P90EodBalance30d'
        }
        /// <summary>
        /// Test the property 'P90EodBalance60d'
        /// </summary>
        [Fact]
        public void P90EodBalance60dTest()
        {
            // TODO unit test for the property 'P90EodBalance60d'
        }
        /// <summary>
        /// Test the property 'P90EodBalance90d'
        /// </summary>
        [Fact]
        public void P90EodBalance90dTest()
        {
            // TODO unit test for the property 'P90EodBalance90d'
        }
        /// <summary>
        /// Test the property 'P10EodBalance30d'
        /// </summary>
        [Fact]
        public void P10EodBalance30dTest()
        {
            // TODO unit test for the property 'P10EodBalance30d'
        }
        /// <summary>
        /// Test the property 'P10EodBalance60d'
        /// </summary>
        [Fact]
        public void P10EodBalance60dTest()
        {
            // TODO unit test for the property 'P10EodBalance60d'
        }
        /// <summary>
        /// Test the property 'P10EodBalance90d'
        /// </summary>
        [Fact]
        public void P10EodBalance90dTest()
        {
            // TODO unit test for the property 'P10EodBalance90d'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Fact]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'CurrentBalance'
        /// </summary>
        [Fact]
        public void CurrentBalanceTest()
        {
            // TODO unit test for the property 'CurrentBalance'
        }
        /// <summary>
        /// Test the property 'BalanceLastUpdated'
        /// </summary>
        [Fact]
        public void BalanceLastUpdatedTest()
        {
            // TODO unit test for the property 'BalanceLastUpdated'
        }
        /// <summary>
        /// Test the property 'PhoneChangeCount28d'
        /// </summary>
        [Fact]
        public void PhoneChangeCount28dTest()
        {
            // TODO unit test for the property 'PhoneChangeCount28d'
        }
        /// <summary>
        /// Test the property 'PhoneChangeCount90d'
        /// </summary>
        [Fact]
        public void PhoneChangeCount90dTest()
        {
            // TODO unit test for the property 'PhoneChangeCount90d'
        }
        /// <summary>
        /// Test the property 'EmailChangeCount28d'
        /// </summary>
        [Fact]
        public void EmailChangeCount28dTest()
        {
            // TODO unit test for the property 'EmailChangeCount28d'
        }
        /// <summary>
        /// Test the property 'EmailChangeCount90d'
        /// </summary>
        [Fact]
        public void EmailChangeCount90dTest()
        {
            // TODO unit test for the property 'EmailChangeCount90d'
        }
        /// <summary>
        /// Test the property 'AddressChangeCount28d'
        /// </summary>
        [Fact]
        public void AddressChangeCount28dTest()
        {
            // TODO unit test for the property 'AddressChangeCount28d'
        }
        /// <summary>
        /// Test the property 'AddressChangeCount90d'
        /// </summary>
        [Fact]
        public void AddressChangeCount90dTest()
        {
            // TODO unit test for the property 'AddressChangeCount90d'
        }

    }

}
