/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing StandaloneInvestmentTransactionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StandaloneInvestmentTransactionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StandaloneInvestmentTransactionType
        //private StandaloneInvestmentTransactionType instance;

        public StandaloneInvestmentTransactionTypeTests()
        {
            // TODO uncomment below to create an instance of StandaloneInvestmentTransactionType
            //instance = new StandaloneInvestmentTransactionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StandaloneInvestmentTransactionType
        /// </summary>
        [Fact]
        public void StandaloneInvestmentTransactionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" StandaloneInvestmentTransactionType
            //Assert.IsType<StandaloneInvestmentTransactionType>(instance);
        }


        /// <summary>
        /// Test the property 'Buy'
        /// </summary>
        [Fact]
        public void BuyTest()
        {
            // TODO unit test for the property 'Buy'
        }
        /// <summary>
        /// Test the property 'Sell'
        /// </summary>
        [Fact]
        public void SellTest()
        {
            // TODO unit test for the property 'Sell'
        }
        /// <summary>
        /// Test the property 'Cancel'
        /// </summary>
        [Fact]
        public void CancelTest()
        {
            // TODO unit test for the property 'Cancel'
        }
        /// <summary>
        /// Test the property 'Cash'
        /// </summary>
        [Fact]
        public void CashTest()
        {
            // TODO unit test for the property 'Cash'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Transfer'
        /// </summary>
        [Fact]
        public void TransferTest()
        {
            // TODO unit test for the property 'Transfer'
        }

    }

}
