/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransferGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferGetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferGetResponse
        //private TransferGetResponse instance;

        public TransferGetResponseTests()
        {
            // TODO uncomment below to create an instance of TransferGetResponse
            //instance = new TransferGetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferGetResponse
        /// </summary>
        [Fact]
        public void TransferGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferGetResponse
            //Assert.IsType<TransferGetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Transfer'
        /// </summary>
        [Fact]
        public void TransferTest()
        {
            // TODO unit test for the property 'Transfer'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
