/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransferAuthorizationCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferAuthorizationCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferAuthorizationCreateRequest
        //private TransferAuthorizationCreateRequest instance;

        public TransferAuthorizationCreateRequestTests()
        {
            // TODO uncomment below to create an instance of TransferAuthorizationCreateRequest
            //instance = new TransferAuthorizationCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferAuthorizationCreateRequest
        /// </summary>
        [Fact]
        public void TransferAuthorizationCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferAuthorizationCreateRequest
            //Assert.IsType<TransferAuthorizationCreateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'AchClass'
        /// </summary>
        [Fact]
        public void AchClassTest()
        {
            // TODO unit test for the property 'AchClass'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'OriginationAccountId'
        /// </summary>
        [Fact]
        public void OriginationAccountIdTest()
        {
            // TODO unit test for the property 'OriginationAccountId'
        }
        /// <summary>
        /// Test the property 'IsoCurrencyCode'
        /// </summary>
        [Fact]
        public void IsoCurrencyCodeTest()
        {
            // TODO unit test for the property 'IsoCurrencyCode'
        }

    }

}
