/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransferAuthorization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferAuthorizationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferAuthorization
        //private TransferAuthorization instance;

        public TransferAuthorizationTests()
        {
            // TODO uncomment below to create an instance of TransferAuthorization
            //instance = new TransferAuthorization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferAuthorization
        /// </summary>
        [Fact]
        public void TransferAuthorizationInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferAuthorization
            //Assert.IsType<TransferAuthorization>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Decision'
        /// </summary>
        [Fact]
        public void DecisionTest()
        {
            // TODO unit test for the property 'Decision'
        }
        /// <summary>
        /// Test the property 'DecisionRationale'
        /// </summary>
        [Fact]
        public void DecisionRationaleTest()
        {
            // TODO unit test for the property 'DecisionRationale'
        }
        /// <summary>
        /// Test the property 'GuaranteeDecision'
        /// </summary>
        [Fact]
        public void GuaranteeDecisionTest()
        {
            // TODO unit test for the property 'GuaranteeDecision'
        }
        /// <summary>
        /// Test the property 'GuaranteeDecisionRationale'
        /// </summary>
        [Fact]
        public void GuaranteeDecisionRationaleTest()
        {
            // TODO unit test for the property 'GuaranteeDecisionRationale'
        }
        /// <summary>
        /// Test the property 'ProposedTransfer'
        /// </summary>
        [Fact]
        public void ProposedTransferTest()
        {
            // TODO unit test for the property 'ProposedTransfer'
        }

    }

}
