/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionsSyncResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionsSyncResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionsSyncResponse
        //private TransactionsSyncResponse instance;

        public TransactionsSyncResponseTests()
        {
            // TODO uncomment below to create an instance of TransactionsSyncResponse
            //instance = new TransactionsSyncResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionsSyncResponse
        /// </summary>
        [Fact]
        public void TransactionsSyncResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionsSyncResponse
            //Assert.IsType<TransactionsSyncResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Added'
        /// </summary>
        [Fact]
        public void AddedTest()
        {
            // TODO unit test for the property 'Added'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Removed'
        /// </summary>
        [Fact]
        public void RemovedTest()
        {
            // TODO unit test for the property 'Removed'
        }
        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
