/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletTransactionAmount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTransactionAmountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletTransactionAmount
        //private WalletTransactionAmount instance;

        public WalletTransactionAmountTests()
        {
            // TODO uncomment below to create an instance of WalletTransactionAmount
            //instance = new WalletTransactionAmount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletTransactionAmount
        /// </summary>
        [Fact]
        public void WalletTransactionAmountInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletTransactionAmount
            //Assert.IsType<WalletTransactionAmount>(instance);
        }


        /// <summary>
        /// Test the property 'IsoCurrencyCode'
        /// </summary>
        [Fact]
        public void IsoCurrencyCodeTest()
        {
            // TODO unit test for the property 'IsoCurrencyCode'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
