/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.64.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletGetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletGetResponse
        //private WalletGetResponse instance;

        public WalletGetResponseTests()
        {
            // TODO uncomment below to create an instance of WalletGetResponse
            //instance = new WalletGetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletGetResponse
        /// </summary>
        [Fact]
        public void WalletGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletGetResponse
            //Assert.IsType<WalletGetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Fact]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
